### ISSUE TITLE
The app crashed when I tried to open a song multiple times.

### ISSUE THREAD

**Issue by sagorahmed** [flackbash/AudioAnchor#10]
#### Expected behavior
I expected that I could open a song multiple times without getting any trouble.

#### Actual behavior
When I tried to open to play a song for a few times, then the app crashed.

#### How to reproduce
Here is every possible detail to reproduce the bug.
1. Open the app.
2. Choose a directory and try to play a song.
3. Then press the back button and try to open that song again. (Repeat this step for a few times.)
4. Notice the crash.

* App version: 1.8.1
* Operating system: Android 6.0.1

#### Recording Of The Bug
![bug](https://media.giphy.com/media/VFB8mNToFIwPtUXDqC/giphy.gif)

#### LogCat
```
06-25 11:57:37.781 23184 23184 D AndroidRuntime: Shutting down VM

06-25 11:57:37.781 23184 23184 E AndroidRuntime: FATAL EXCEPTION: main

06-25 11:57:37.781 23184 23184 E AndroidRuntime: Process: com.prangesoftwaresolutions.audioanchor, PID: 23184

06-25 11:57:37.781 23184 23184 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 23040012 byte allocation with 6395496 free bytes and 6MB until OOM

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:856)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:675)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:703)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:733)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at com.prangesoftwaresolutions.audioanchor.MediaPlayerService.updateMetaData(MediaPlayerService.java:491)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at com.prangesoftwaresolutions.audioanchor.MediaPlayerService.initMediaSession(MediaPlayerService.java:401)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at com.prangesoftwaresolutions.audioanchor.MediaPlayerService.onStartCommand(MediaPlayerService.java:155)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4128)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.app.ActivityThread.access$2400(ActivityThread.java:229)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

06-25 11:57:37.781 23184 23184 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by flackbash** [comment]
Thanks for reporting this. I could not reproduce the bug but I'll have a look at it still and see if I can find the problem.

**Comment by sagorahmed** [comment]
Hi @flackbash 
Nice to have you on this issue. 
Don't know why this issue is not occurring on your phone. But on my phone, there are some other issues with the same log of the app
```java.lang.OutOfMemoryError: Failed to allocate a 23040012 byte allocation with 6395496 free bytes and 6MB until OOM```
Hopefully, you will come to an end this issue in the near future.

**Comment by flackbash** [comment]
I found the problem, but I'm not sure whether it's completely solved. Could you check whether you can still reproduce the bug after commit ca60651? At the very least it should occur less often.
If you need me to send you an apk let me know.
