### ISSUE TITLE
Crashing on dev build when attempting to play any audio file

### ISSUE THREAD

**Issue by Twinov** [flackbash/AudioAnchor#149]
Device: Pixel 6 Pro  
Android Version: 12  

I went through the git commits and noticed that ever since b95cf0756bedd6174d584ab4137c04e0b6c3153e, my app crashes when attempting to play any audio file. I can consistently reproduce the issue every time by clicking ▶️ on any audio file. I've restarted and cleared the app data and the issue persists.  

Here's a log of the crash from Android Studio:  
```
2022-03-13 10:37:18.200 7090-7090/com.prangesoftwaresolutions.audioanchor V/GraphicsEnvironment: ANGLE Developer option for 'com.prangesoftwaresolutions.audioanchor' set to: 'default'
2022-03-13 10:37:18.200 7090-7090/com.prangesoftwaresolutions.audioanchor V/GraphicsEnvironment: ANGLE GameManagerService for com.prangesoftwaresolutions.audioanchor: false
2022-03-13 10:37:18.200 7090-7090/com.prangesoftwaresolutions.audioanchor V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
2022-03-13 10:37:18.201 7090-7090/com.prangesoftwaresolutions.audioanchor D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-03-13 10:37:18.118 7090-7090/com.prangesoftwaresolutions.audioanchor D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10470; state: ENABLED
2022-03-13 10:37:18.201 7090-7090/com.prangesoftwaresolutions.audioanchor D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-03-13 10:37:18.214 7090-7118/com.prangesoftwaresolutions.audioanchor D/mali_cmarp_predictor: checking cmar_predictor for com.prangesoftwaresolutions.audioanchor
2022-03-13 10:37:18.256 7090-7090/com.prangesoftwaresolutions.audioanchor W/ons.audioancho: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2022-03-13 10:37:18.256 7090-7090/com.prangesoftwaresolutions.audioanchor W/ons.audioancho: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2022-03-13 10:37:18.268 7090-7090/com.prangesoftwaresolutions.audioanchor D/CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10470; state: ENABLED
2022-03-13 10:37:18.290 7090-7090/com.prangesoftwaresolutions.audioanchor E/AlbumActivity: service bound: falsedo not bind service: false
2022-03-13 10:37:18.292 7090-7090/com.prangesoftwaresolutions.audioanchor E/AlbumActivity: Service is running - binding service
2022-03-13 10:37:18.298 7090-7090/com.prangesoftwaresolutions.audioanchor E/AlbumActivity: service bound: truedo not bind service: false
2022-03-13 10:37:18.312 7090-7090/com.prangesoftwaresolutions.audioanchor D/CompatibilityChangeReporter: Compat change id reported: 147600208; UID 10470; state: ENABLED
2022-03-13 10:37:18.313 7090-7090/com.prangesoftwaresolutions.audioanchor D/AndroidRuntime: Shutting down VM
2022-03-13 10:37:18.314 7090-7090/com.prangesoftwaresolutions.audioanchor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.prangesoftwaresolutions.audioanchor, PID: 7090
    java.lang.RuntimeException: Unable to create service com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService: java.lang.SecurityException: listen
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
        at android.app.ActivityThread.access$1700(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.SecurityException: listen
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
        at android.telephony.TelephonyRegistryManager.listenFromListener(TelephonyRegistryManager.java:250)
        at android.telephony.TelephonyManager.listen(TelephonyManager.java:6000)
        at com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService.callStateListener(MediaPlayerService.java:564)
        at com.prangesoftwaresolutions.audioanchor.services.MediaPlayerService.onCreate(MediaPlayerService.java:149)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)
        at android.app.ActivityThread.access$1700(ActivityThread.java:247) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by Twinov** [comment]
After a little bit of digging, seems that [this line](https://github.com/flackbash/AudioAnchor/blob/b95cf0756bedd6174d584ab4137c04e0b6c3153e/app/src/main/java/com/prangesoftwaresolutions/audioanchor/services/MediaPlayerService.java#L149) is causing the issue due to `telephonyManager.listen` being deprecated in SDK version 31. [Android docs](https://developer.android.com/reference/android/telephony/TelephonyManager#listen(android.telephony.PhoneStateListener,%20int))

**Comment by flackbash** [comment]
Thanks for pointing it out and looking into it :)

I'll probably roll back the targetSdkVersion to 30, since it seems like the deprecated PhoneStateListener is not the only problem that's introduced and I don't have time for a lot of changes at the moment.
